%% Overlapping Compartmental Formulation with Incomplete Cross-Protection
% Deterministic four-strain multilocus immune-history model

% Partial Epitope Coverage = PEC = P1 and P2, Full Epitope Coverage = FEC = P3

% Strains are defined by two loci: ax, ay, bx, by

% Immune outcomes are channeled through the following probabilities:
% P1 = locus 1 / PEC response: a or b
% P2 = locus 2 / PEC response: x or y
% P3 = locus 1 and locus 2 / FEC response: ax, ay, bx, or by

% gamma controls the degree of cross-protection between strains sharing
% one epitope. Infection risk against partially cross-protected strains is
% scaled by (1 - gamma).

% Instead of explicitly tracking every immune history, hosts are represented
% through overlapping epidemiological variables:
% Y_ij : proportion currently infected with strain ij

% Z_ij : proportion previously exposed to exact strain ij

% W_ij : proportion previously exposed to any strain sharing at least one
% epitope with ij

% W_a, W_b, W_x, W_y : proportions previously exposed to individual
% epitope classes

% V_ij is calculated algebraically as the residual host class possessing
% overlapping but non-exclusive immune histories relevant to strain ij

% Setting up ODE function
function [T,Y] = MANTIS_EpitopeSpecific_X4(mu, beta_ax, beta_ay, beta_bx, beta_by, sigma, gamma, P1, P2, P3, time)

% Pack model parameters
pars=[mu,beta_ax,beta_ay,beta_bx,beta_by,sigma,gamma,P1,P2,P3];  

% Initial conditions:
% seed each strain at low prevalence; all immune-history variables begin at zero.
init_pop = zeros(16,1);
init_pop(1:4) = [0.0005, 0.0005, 0.0005, 0.0005];

% Specify use of ODE45 numerical solver, start at zero, steps of 3/360, ends at time
[T,Y]= ode45(@equations, 0:0.001:time, init_pop,odeset('nonnegative',1:16,'AbsTol', 1e-14), pars);  
end % end main function

% Define ODE eRuations
function dydt = equations(~,y,pars)

% Unpack Parameters back to original names 
mu = pars(1);
beta_ax = pars(2);
beta_ay = pars(3);
beta_bx = pars(4);
beta_by = pars(5);
sigma = pars(6); 
gamma = pars(7); 
P1 = pars(8);
P2 = pars(9);
P3 = pars(10);

% Unpack state variables
% Y compartments track active infection
% Z compartments track exact strain exposure
% W compartments track overlapping exposure to shared epitope sets

Y_ax = y(1); Y_ay = y(2); 
Y_bx = y(3); Y_by = y(4); 

Z_ax = y(5); Z_ay = y(6); 
Z_bx = y(7); Z_by = y(8); 

W_ax = y(9); W_ay = y(10); 
W_bx = y(11); W_by = y(12); 

W_a = y(13); W_b = y(14);
W_x = y(15); W_y = y(16);

% compute V as algebraic diagnostics 
V_ax = W_ax - Z_ax - (W_ax - W_a) - (W_ax - W_x);
V_ay = W_ay - Z_ay - (W_ay - W_a) - (W_ay - W_y);

V_bx = W_bx - Z_bx - (W_bx - W_b) - (W_bx - W_x);
V_by = W_by - Z_by - (W_by - W_b) - (W_by - W_y);

% forces of infection generated by multiplying the transmission
% parameter by the proportion of individuals infected
lambda_ax = beta_ax*Y_ax;
lambda_ay = beta_ay*Y_ay;

lambda_bx = beta_bx*Y_bx;
lambda_by = beta_by*Y_by;

% infecteds (strains ax, bx, ay, by)
dY_ax = lambda_ax*((1 - W_ax) + (P2 + (1 - gamma)*P3)*(W_ax - W_x) + (P1 + ((1 - gamma)*P3))*(W_ax - W_a) + (P1*P2 + (1 - gamma)*(P3^2 + 2*P1*P3 + 2*P2*P3))*V_ax) - Y_ax*(sigma + mu);
dY_ay = lambda_ay*((1 - W_ay) + (P2 + (1 - gamma)*P3)*(W_ay - W_y) + (P1 + ((1 - gamma)*P3))*(W_ay - W_a) + (P1*P2 + (1 - gamma)*(P3^2 + 2*P1*P3 + 2*P2*P3))*V_ay) - Y_ay*(sigma + mu);

dY_bx = lambda_bx*((1 - W_bx) + (P2 + (1 - gamma)*P3)*(W_bx - W_x) + (P1 + ((1 - gamma)*P3))*(W_bx - W_b) + (P1*P2 + (1 - gamma)*(P3^2 + 2*P1*P3 + 2*P2*P3))*V_bx) - Y_bx*(sigma + mu);
dY_by = lambda_by*((1 - W_by) + (P2 + (1 - gamma)*P3)*(W_by - W_y) + (P1 + ((1 - gamma)*P3))*(W_by - W_b) + (P1*P2 + (1 - gamma)*(P3^2 + 2*P1*P3 + 2*P2*P3))*V_by) - Y_by*(sigma + mu);


% previously exposed to specific immunological combinations (Z_ax, Z_bx, Z_ay, Z_by)
dZ_ax = (lambda_ax)*(1 - Z_ax) - mu*Z_ax;
dZ_ay = (lambda_ay)*(1 - Z_ay) - mu*Z_ay;

dZ_bx = (lambda_bx)*(1 - Z_bx) - mu*Z_bx;
dZ_by = (lambda_by)*(1 - Z_by) - mu*Z_by;

% previously exposed to strains which share any immunological features (W_ax, W_bx, W_ay, W_by)
dW_ax = (lambda_ax + lambda_ay + lambda_bx)*(1 - W_ax) - mu*W_ax;
dW_ay = (lambda_ay + lambda_ax + lambda_by)*(1 - W_ay) - mu*W_ay;

dW_bx = (lambda_bx + lambda_by + lambda_ax)*(1 - W_bx) - mu*W_bx;
dW_by = (lambda_by + lambda_bx + lambda_ay)*(1 - W_by) - mu*W_by;

dW_a = (lambda_ax + lambda_ay)*(1 - W_a) - mu*W_a;
dW_b = (lambda_bx + lambda_by)*(1 - W_b) - mu*W_b;

dW_x = (lambda_ax + lambda_bx)*(1 - W_x) - mu*W_x;
dW_y = (lambda_ay + lambda_by)*(1 - W_y) - mu*W_y;

% Assemble derivatives in the same order as the state vector y.
dydt = [
    dY_ax;
    dY_ay;
    
    dY_bx;
    dY_by;
    
    dZ_ax;
    dZ_ay;
   
    dZ_bx;
    dZ_by;
   
    dW_ax;
    dW_ay;
    
    dW_bx;
    dW_by;
    
    dW_a;
    dW_b;
    
    dW_x;
    dW_y];

end



